### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/timebank-dense.yuchen-tdt.test.stage2--parsed-labeled.'

### ISSUE THREAD

**Issue by chuangdang-vue** [bnmin/tdp_ranking#2]
parse.py: error: argument --classifier: expected one argument
eval test data ...
Traceback (most recent call last):
  File "/home/byh452/tdp_ranking/eval.py", line 215, in <module>
    parsed_tuples = read_in_tuples(args.parsed_file)
  File "/home/byh452/tdp_ranking/eval.py", line 25, in read_in_tuples
    lines = codecs.open(filename, 'r', 'utf-8').readlines()
  File "/home/byh452/anaconda3/envs/py_3.7/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/timebank-dense.yuchen-tdt.test.stage2--parsed-labeled.'
unlabeled evaluations on test data ...
Traceback (most recent call last):
  File "/home/byh452/tdp_ranking/eval.py", line 215, in <module>
    parsed_tuples = read_in_tuples(args.parsed_file)
  File "/home/byh452/tdp_ranking/eval.py", line 25, in read_in_tuples
    lines = codecs.open(filename, 'r', 'utf-8').readlines()
  File "/home/byh452/anaconda3/envs/py_3.7/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/timebank-dense.yuchen-tdt.test.stage2--parsed-labeled.'

**Comment by rossh2** [comment]
It looks like you didn't pass the classifier argument to the script, which caused `parse.py` to fail. This means it didn't produce any output and so the rest of the script, which expects output files in certain locations, gave you this error.

Assuming you're using `run-exp.sh` then the fourth argument should be the name of the classifier you want to use, namely one of "bilstm", "glove_bilstm", "bert_bilstm", "bert_as_classifier", "bert_as_classifier_alt" or "baseline" (this is documented in the Readme and also in `parse.py`). These are the different models that we tested. If you're looking for the one we reported in the paper as doing the best, use "bert_as_classifier". 

Hope that helps!
